# Generated by Django 4.2.5 on 2023-09-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_clientmailing_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmailing',
            name='users',
        ),
    ]
